[phases.setup]
nixPkgs = [
  "nodejs_20",
  "cairo",
  "pango",
  "libpng",
  "libjpeg",
  "giflib",
  "librsvg",
  "pkg-config",
  "pixman",
  "python3",
  "sqlite"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []

[start]
cmd = "npm start"
